steps:
  - name: 'maven:3-jdk-11'
    args:
      - clean
      - package
    dir: my-service
    entrypoint: mvn
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        asia-south2-docker.pkg.dev/myproject/my-artifactory/backend:serviceimage
      - .
    dir: my-service
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        asia-south2-docker.pkg.dev/myproject/my-artifactory/backend:serviceimage
    dir: my-service
    id: Push
